language: node_js
node_js:
- 10.16.0
branches:
  only:
  - production
cache:
  yarn: true
  directories: "$HOME/google-cloud-sdk"

before_install:
  - openssl aes-256-cbc -K $encrypted_a7e9b599f877_key -iv $encrypted_a7e9b599f877_iv -in secret.json.enc -out secret.json -d

install:
  - yarn

deploy:
  provider: script
  skip_cleanup: true
  script: npm run publish
  on: production